language: node_js
os:
  - linux
  - osx
node_js:
  - "8"
jobs:
  include:
    - stage: install
      script: yarn cli:build
    - stage: test
      script: yarn cli:test
cache:
  directories:
    - node_modules
