language: node_js
os:
  - linux
  - osx
node_js:
  - "8"
jobs:
  include:
    - stage: install
	  name: "CLI install"
      script: yarn cli:build
    - stage: test
	  name: "CLI test"
      script: yarn cli:test
cache:
  directories:
    - node_modules
